---
# tasks file for openvpn (Ubuntu specific)

- name: Install OpenVPN GPG key
  become: yes
  apt_key:
    url: https://swupdate.openvpn.net/repos/repo-public.gpg
    state: present
  tags:
    - openvpn

- name: Add OpenVPN repository
  become: yes
  apt_repository:
    repo: 'deb http://swupdate.openvpn.net/apt trusty main'
    state: present
  tags:
    - openvpn

- name: Install OpenVPN packages
  become: yes
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - "{{ openvpn_packages }}"
  tags:
    - openvpn
