---
# handlers file for openvpn

- name: restart openvpn
  become: yes
  service:
    name: "{{ openvpn_service_name }}"
    state: restarted
  tags:
    - openvpn

- name: stop openvpn
  become: yes
  service:
    name: "{{ openvpn_service_name }}"
    state: stopped
  tags:
    - openvpn
